//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Database1Model", "FK__Absen__nik__0519C6AF", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TugasKLG_OenJanJason.Model.Employee), "Absen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TugasKLG_OenJanJason.Model.Absen), true)]

#endregion

namespace TugasKLG_OenJanJason.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Database1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Database1Entities object using the connection string found in the 'Database1Entities' section of the application configuration file.
        /// </summary>
        public Database1Entities() : base("name=Database1Entities", "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(string connectionString) : base(connectionString, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(EntityConnection connection) : base(connection, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Absen> Absens
        {
            get
            {
                if ((_Absens == null))
                {
                    _Absens = base.CreateObjectSet<Absen>("Absens");
                }
                return _Absens;
            }
        }
        private ObjectSet<Absen> _Absens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Absens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbsens(Absen absen)
        {
            base.AddObject("Absens", absen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Absen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Absen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Absen object.
        /// </summary>
        /// <param name="nik">Initial value of the nik property.</param>
        /// <param name="tanggal">Initial value of the tanggal property.</param>
        public static Absen CreateAbsen(global::System.String nik, global::System.DateTime tanggal)
        {
            Absen absen = new Absen();
            absen.nik = nik;
            absen.tanggal = tanggal;
            return absen;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nik
        {
            get
            {
                return _nik;
            }
            set
            {
                if (_nik != value)
                {
                    OnnikChanging(value);
                    ReportPropertyChanging("nik");
                    _nik = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nik");
                    OnnikChanged();
                }
            }
        }
        private global::System.String _nik;
        partial void OnnikChanging(global::System.String value);
        partial void OnnikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime tanggal
        {
            get
            {
                return _tanggal;
            }
            set
            {
                if (_tanggal != value)
                {
                    OntanggalChanging(value);
                    ReportPropertyChanging("tanggal");
                    _tanggal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tanggal");
                    OntanggalChanged();
                }
            }
        }
        private global::System.DateTime _tanggal;
        partial void OntanggalChanging(global::System.DateTime value);
        partial void OntanggalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK__Absen__nik__0519C6AF", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("Database1Model.FK__Absen__nik__0519C6AF", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("Database1Model.FK__Absen__nik__0519C6AF", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("Database1Model.FK__Absen__nik__0519C6AF", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("Database1Model.FK__Absen__nik__0519C6AF", "Employee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="nik">Initial value of the nik property.</param>
        public static Employee CreateEmployee(global::System.String nik)
        {
            Employee employee = new Employee();
            employee.nik = nik;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nik
        {
            get
            {
                return _nik;
            }
            set
            {
                if (_nik != value)
                {
                    OnnikChanging(value);
                    ReportPropertyChanging("nik");
                    _nik = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nik");
                    OnnikChanged();
                }
            }
        }
        private global::System.String _nik;
        partial void OnnikChanging(global::System.String value);
        partial void OnnikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nama
        {
            get
            {
                return _nama;
            }
            set
            {
                OnnamaChanging(value);
                ReportPropertyChanging("nama");
                _nama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nama");
                OnnamaChanged();
            }
        }
        private global::System.String _nama;
        partial void OnnamaChanging(global::System.String value);
        partial void OnnamaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK__Absen__nik__0519C6AF", "Absen")]
        public EntityCollection<Absen> Absens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Absen>("Database1Model.FK__Absen__nik__0519C6AF", "Absen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Absen>("Database1Model.FK__Absen__nik__0519C6AF", "Absen", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
